### PR TITLE
Adds callback for completion of file merge

### PR DESCRIPTION
**Pull request by benjaminknox**
I need to know when the process is completely done creating the sprite and there isn't a way to do that currently, this change adds a callback called on the completion of the file merge.

### CODE REVIEW

**Comment by sunny** [comment]
Hey @benjaminknox, sounds good to me! Thank you! 👍

**Comment by sunny** [comment]
v3.2.0 released with the change 🎉

**Comment by bknoxphysna** [comment]
Thank you.

**Comment by benjaminknox** [comment]
Thank you!

**Pull request merged**
